name: audiobook_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  cached_network_image: ^3.3.1
  get_it: ^7.6.7
  dio: ^5.4.1
  http: ^0.13.3
  flutter_bloc: ^8.1.3
  dartz: ^0.10.1
  equatable: ^2.0.5
  rxdart: ^0.27.7
  sqflite: ^2.3.2
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  provider: ^6.1.2
  path: ^1.9.0
  audio_service: ^0.18.12
  just_audio: ^0.9.36

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6

flutter:

  uses-material-design: true
